// codeGenerator.js — Convert React Flow circuit graph → Perceval Python code

/**
 * Topological sort of nodes by their x-position (left → right = circuit order).
 */
function sortByPosition(nodes) {
  return [...nodes].sort((a, b) => a.position.x - b.position.x);
}

/**
 * Assign sequential mode indices to node handles.
 * Each BS gets 2 modes; PS/Mirror/Source get 1.
 */
function assignModes(sortedNodes) {
  let modeCounter = 0;
  const modeMap = {}; // nodeId → { in: [modes], out: [modes] }

  for (const node of sortedNodes) {
    if (node.type === 'bs') {
      modeMap[node.id] = { in: [modeCounter, modeCounter + 1], out: [modeCounter, modeCounter + 1] };
      modeCounter += 2;
    } else if (node.type === 'source') {
      const count = node.data.photons || 1;
      const modes = Array.from({ length: count }, (_, i) => modeCounter + i);
      modeMap[node.id] = { in: modes, out: modes };
      modeCounter += count;
    } else {
      // ps, mirror — single mode
      modeMap[node.id] = { in: [modeCounter], out: [modeCounter] };
      modeCounter += 1;
    }
  }
  return { modeMap, totalModes: modeCounter };
}

/**
 * Generate the Perceval Python code string from nodes + edges.
 * @param {object[]} nodes
 * @param {object[]} edges
 * @returns {string}
 */
export function generatePercevalCode(nodes, edges) {
  if (!nodes || nodes.length === 0) {
    return '# Add components to the canvas to generate code';
  }

  const sources = nodes.filter((n) => n.type === 'source');
  const components = nodes.filter((n) => n.type !== 'source');
  const sorted = sortByPosition(components);
  const allSorted = [...sources, ...sorted];
  const { modeMap, totalModes } = assignModes(allSorted);

  const lines = [
    'import perceval as pcvl',
    'import math',
    '',
    `# Generated by Perceval Composer — ${new Date().toISOString().split('T')[0]}`,
    `circuit = pcvl.Circuit(${Math.max(totalModes, 1)})`,
    '',
  ];

  // Component adds
  for (const node of sorted) {
    const modes = modeMap[node.id];
    if (!modes) continue;
    const m0 = modes.in[0];

    if (node.type === 'bs') {
      const theta = (node.data.theta ?? Math.PI / 4).toFixed(6);
      lines.push(`# ${node.data.label || 'Beam Splitter'}`);
      lines.push(`circuit.add(${m0}, pcvl.BS(theta=${theta}))`);
    } else if (node.type === 'ps') {
      const phi = (node.data.phi ?? 0).toFixed(6);
      lines.push(`# ${node.data.label || 'Phase Shifter'}`);
      lines.push(`circuit.add(${m0}, pcvl.PS(phi=${phi}))`);
    } else if (node.type === 'mirror') {
      lines.push(`# ${node.data.label || 'Mirror'}`);
      lines.push(`circuit.add(${m0}, pcvl.PERM([1, 0]))  # Mirror / SWAP`);
    }
    lines.push('');
  }

  // Input state from source nodes
  const photonList = Array(Math.max(totalModes, 1)).fill(0);
  for (const src of sources) {
    const modes = modeMap[src.id];
    if (modes) {
      modes.in.forEach((m) => { photonList[m] = 1; });
    }
  }

  lines.push(`# Input state`);
  lines.push(`input_state = pcvl.BasicState([${photonList.join(', ')}])`);
  lines.push('');
  lines.push('# Simulation');
  lines.push(`backend = pcvl.BackendFactory.get_backend("Naive")`);
  lines.push(`backend.set_circuit(circuit)`);
  lines.push(`backend.set_input_state(input_state)`);
  lines.push('');
  lines.push('# Compute probability distribution');
  lines.push('_result = backend.prob_distribution()');
  lines.push('');
  lines.push('# Print results');
  lines.push('for state, prob in _result.items():');
  lines.push('    p = float(prob)');
  lines.push('    if p > 1e-6:');
  lines.push('        print(f"|{state}> : {p:.6f}")');

  return lines.join('\n');
}
